version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9080:9080"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/hits
      - SPRING_DATASOURCE_USERNAME=tbdggr
      - SPRING_DATASOURCE_PASSWORD=121065
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-client:
    build: stats/stats-client
    image: stats-client-image
    container_name: stats-client-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9080

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "5432:5432"
    volumes:
      - ./stats/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=hits
      - POSTGRES_PASSWORD=121065
      - POSTGRES_USER=tbdggr

  ewm-service:
    build: main-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - stats-client
      - ewm-db
    environment:
      - STATS_CLIENT_URL=http://stats-client:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=tbdggr
      - SPRING_DATASOURCE_PASSWORD=151142
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "8090:8090"
    volumes:
      - ./main-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_PASSWORD=151142
      - POSTGRES_USER=tbdggr